# _config.yml

# Site settings
title: My Jekyll Site
description: A simple and elegant Jekyll site
url: "https://hubertiwan.github.io"  # Replace with your GitHub Pages URL

# GitHub Pages settings
baseurl: ""  # Leave it empty if your site is at the root of your domain

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Author information
author:
  name: Your Name
  bio: Web Developer and Blogger
  email: your.email@example.com
  twitter: your_twitter_handle
  github: yourusername
  linkedin: your-linkedin-profile

# Social media links
social:
  - title: Twitter
    url: https://twitter.com/your_twitter_handle
  - title: GitHub
    url: https://github.com/yourusername
  - title: LinkedIn
    url: https://www.linkedin.com/in/your-linkedin-profile
