# _config.yml

# Site settings
title: hubertiwan's GitHub Pages site
description: A simple and elegant Jekyll site
url: "https://hubertiwan.github.io"  # Replace with your GitHub Pages URL

# GitHub Pages settings
baseurl: ""  # Leave it empty if your site is at the root of your domain

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Author information
author:
  name: Hubert
  bio: Cybersecurity student 
  github: hubertiwan
  linkedin: www.linkedin.com/in/hubert-iwanowski-727106218

